### ISSUE TITLE
Convert to v2 addon

### ISSUE THREAD

**Issue by SergeAstapov** [pzuraq/tracked-maps-and-sets#223]
As this addon provides only run-time functionality hence it's the great candidate for v2 addon conversion.

This would require major release.

@chriskrycho any thoughts, concerns?

**Comment by chriskrycho** [comment]
In general, I’m strongly in support. My main hesitation is timing: we *just* cut a major fairly recently, and folks have had issues because there's a coordination challenge with this, tracked-built-ins, and tracked-toolbox. My current thinking is: it's totally fine to go ahead and do, and we can even cut a beta for the next major, but we should wait to major until we drop Node 12 support when it goes out of LTS support at the end of April. Feel free to knock this out and we can get the beta out to unblock people!

**Comment by chriskrycho** [comment]
Per https://github.com/tracked-tools/tracked-built-ins/issues/274#issuecomment-1067508096, let's actually *not* do this and resolve it by way of pulling this functionality entirely into tracked-built-ins (as part of the implementation prep work to unblock whatever iteration on emberjs/rfcs#812 we end up merging!).
